# The Figaro gem is used for configuration instead of secrets.yml
# https://github.com/laserlemon/figaro
# Duplicate application.sample.yml as application.yml and insert the required
# values.

database_encryption_key: CHANGE_ME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
detect_language_key: optional
devise_secret_key: CHANGE_ME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
evernote_key: CHANGE_ME
evernote_secret: CHANGE_ME
evernote_username: CHANGE_ME
facebook_key: optional
facebook_secret: optional
github_key: optional
github_secret: optional
github_secret: optional
gplus_key: optional
isbndb_key: optional
linkedin_key: optional
linkedin_secret: optional 
mailer_address: CHANGE_ME
mailer_domain: CHANGE_ME
mailer_password: CHANGE_ME
mailer_port: CHANGE_ME
mailer_user_name: optional
secret_key_base: CHANGE_ME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
twitter_key: optional
twitter_pantography_access_secret: optional
twitter_pantography_access_token: optional
twitter_pantography_key: optional
twitter_pantography_secret: optional
twitter_secret: optional
world_cat_key: optional
