defaults: &defaults
  channel:
    evernote_notebooks: f63f25b7-0c4f-4541-afb3-7286d72e452b
    name: joegatt.net

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
  channel:
    evernote_notebooks: 85d8c66d-f0ee-4c56-acac-e30ab88ce0ce,53bcb1f5-93c0-42fd-b28c-a326f57b75c6,b6ca0bf4-d658-4d8f-a535-69251298687a
    name: joegatt.net
