defaults: &defaults
  admin_email: joe@joegatt.net
  admin_name: Joe
  app_name: joegattnet
  assets_version: 1.3
  blank_image_location: '/public/resources/cut/blank.png'
  cache_buster: 1
  cache_minutes: 10
  daemon_frequency: 30
  detect_language_sample_length: 250
  evernote_errors: ['', 'UNKNOWN', 'BAD_DATA_FORMAT', 'PERMISSION_DENIED', 'INTERNAL_ERROR', 'DATA_REQUIRED', 'LIMIT_REACHED', 'QUOTA_REACHED', 'INVALID_AUTH', 'AUTH_EXPIRED', 'DATA_CONFLICT', 'ENML_VALIDATION', 'SHARD_UNAVAILABLE', 'LEN_TOO_SHORT', 'LEN_TOO_LONG', 'TOO_FEW', 'TOO_MANY', 'UNSUPPORTED_OPERATION']
  html:
    pretty: true
    pretty_body: false
    sort_attrs: true
    tabsize: 2
    format: html5
  mailer:
    address: smtp.gmail.com
    port: 587
    domain: mail.joegatt.net
  repository: git://github.com/joegattnet/joegattnet_v3.git
  role_name: joegatt.net
  rtl_langs: 'ar fa'
  stream_binaries: false
  synchronous: false
  version: 0.9

development:
  <<: *defaults
  host: localhost:3000
  synchronous: true
  cache_minutes: 0

test:
  <<: *defaults
  host: rspec-tests
  cache_minutes: 0

staging:
  <<: *defaults
  host: staging.joegatt.net
  asset_host: http://a4.joegatt.org/
  synchronous: true

production:
  <<: *defaults
  host: joegatt.net
  asset_host: http://a3.joegatt.org/
