defaults: &defaults
  pantography:
    alphabet: 0123456789.,;:_@!?/#()%'-+= abcdefghijklmnopqrstuvwxyz
    alphabet_escaped: 0123456789.,;:_@!?/#()%'\-+= abcdefghijklmnopqrstuvwxyz
    start_date: 'October 28, 2011 08:20:00 GMT'
    frequency: 3600
    max_length: 140
    sidereal_year_in_days: 365.256363004
    timeline_length: 20
    twitter_user_id: 66855083

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
  pantography:
    alphabet: 0123456789.,;:_@!?/#()%'-+= abcdefghijklmnopqrstuvwxyz
    alphabet_escaped: 0123456789.,;:_@!?/#()%'\-+= abcdefghijklmnopqrstuvwxyz
    start_date: 'October 28, 2011 08:20:00 GMT'
    frequency: 3600
    max_length: 140
    sidereal_year_in_days: 365.256363004
    timeline_length: 20
    twitter_user_id: 394339242
