defaults: &defaults
  style:
    background_color: '#fafafa'
    body_font: Bitter
    body_font_color: '#222'
    body_font_fallback: 'Georgia, serif'
    body_font_size: 18px
    border_color: '#ccc'
    caption_color: '#454545'
    citation_font: SourceSansPro
    citation_font_color: '#222'
    citation_font_fallback: 'Arial, sans-serif'
    citation_style: default
    code_font: Inconsolata
    code_font_fallback: 'Courier, monospace'
    column_width: 60
    container_style: magic
    count_color: '#900'
    css_for_instructions: __FX_POL __SECTION __ENUMERATE  __CURTAIN __CURTAIN_50 __CURTAIN_75 __CURTAIN_100 __CURTAIN_0 __HIDE_HEADER __SHOW_BYLINE
    delete_font_color: '#222'
    error_background_color: '#ff4545'
    evernote_color: '#61b737'
    external_link_hover_color: '#009'
    facebook_color: '#3b5998'
    font: SourceSansPro
    font_color: '#222'
    font_fallback: 'Arial, sans-serif'
    font_size: 18px
    force_double_quotes: true
    furniture_color: '#666'
    github_color: '#201f1f'
    gplus_color: '#dd4b39'
    grid_padding: 0
    gutter_width: 28
    headline_font: SourceSansPro
    headline_font_color: '#900'
    headline_font_fallback: 'Arial, sans-serif'
    headline_font_size: 28px
    hyper_conform: false
    images_cinema_aspect_x: 27
    images_cinema_aspect_y: 10
    images_cinema_width: 12
    images_effects:
    images_expanded_width: 1400
    images_full_aspect_x: 16
    images_full_aspect_y: 9
    images_full_width: 2000
    images_gravity: 0
    images_min_width: 799
    images_name_length: 30
    images_snap: 0
    images_standard_aspect_x: 16
    images_standard_aspect_y: 9
    images_standard_width: 8
    images_thumbnail_aspect_x: 16
    images_thumbnail_aspect_y: 9
    images_thumbnail_width: 3
    insert_background_color: '#ffff45'
    invalid_background_color: '#ff0'
    line_height: 28px
    link_color: '#222'
    link_hover_color: '#900'
    link_visited_color: '#222'
    linkedin_color: '#1c87bd'
    map_background_color: '#ccc'
    map_font_color: '#333'
    note_images_number: 1
    off_color: '#999'
    promotions_footer: 6
    promotions_home_columns: 3
    promotions_home_lines: 7
    promotions_home_rows: 2
    promotions_home_show_image?: false
    qr_code_image_size: 150
    row_hover_color: '#ff0'
    secondary_color: '#333'
    selected_background_color: '#ff0'
    selected_font_color: '#222'
    small_font_size: 13px
    static_url_color: '#090'
    success_background_color: '#45ff45'
    total_columns: 12
    total_width: 100%
    twitter_color: '#00acee'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
