# All Nembrot settings go here except for secret strings

defaults: &defaults
  styling:
    colors:
      red: '#900'
      green: '#090'
      blue: '#009'
    background_color: '#fff'
    body_font: 'NOT USED'
    body_font_citation_color: '#000'
    body_font_citation_family: 'DejaVuSansCondensed, Arial, Helvetica, sans-serif'
    body_font_citation_size: '15px'
    body_font_color: '#000'
    body_font_family: 'Georgia, serif'
    body_font_size: '18px'
    body_font_variant: 'regular'
    caption_color: '#454545'
    citation_style: 'default'
    column_width: 60
    total_columns: 12
    container_style: magic
    grid_padding: 0
    count_color: '#900'
    css_for_instructions: ['__FX_POL']
    delete_font_color: '#000'
    error_background_color: '#ff4545'
    font_color: '#000'
    font_family: 'DejaVuSansCondensed, Arial, Helvetica, sans-serif'
    font_size: '15px'
    furniture_color: '#666'
    gutter_width: 30
    headline_font: 'DejaVuSansCondensed'
    headline_font_color: '#900'
    headline_font_family: 'DejaVuSansCondensed, Arial, Helvetica, sans-serif'
    headline_font_size: '36px'
    headline_font_variant: 'condensed_book'
    insert_background_color: '#ffff45'
    invalid_background_color: 'ff0'
    line_height: 30
    link_color: '#000'
    link_hover_color: '#009'
    link_visited_color: '#000'
    map_background_color: '#ccc'
    map_font_color: '#333'
    monospace_font: 'DejaVuMonoBook'
    monospace_font_variant: 'mono_book'
    monospace_font_family: 'DejaVuMonoBook, monospace'
    off_color: '#999'
    qr_code_image_size: 150
    secondary_color: '#333'
    selected_background_color: '#ff0'
    selected_font_color: '#000'
    small_font_size: '13px'
    static_url_color: '#090'
    success_background_color: '#45ff45'
    total_width: '100%'
    images:
      effects:
      name_length: 30
      snap: 1
      gravity: 0
      standard:
        aspect:
          x: 16
          y: 9
        width: 8
      cinema:
        aspect:
          x: 27
          y: 10
        width: 12
      thumbnail:
        aspect:
          x: 16
          y: 9
        width: 3
      expanded:
        width: 1400

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
